version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - python -m venv env
      - source env/bin/activate
      - pip install --upgrade pip
      - pip install fastapi uvicorn pytest httpx  

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      - pip install -r requirements.txt || echo "No requirements.txt found, skipping"
      - echo "Installing test dependencies..."
      - pip install pytest

  build:
    commands:
      - echo "Running tests..."
      - pytest tests/ --junitxml=results.xml
      - echo "Building the application..."
      - mkdir -p artifact
      - cp -r app.py static/ artifact/

  post_build:
    commands:
      - echo "Post-build steps completed."
      - echo "Build successful!"

artifacts:
  files:
    - artifact/**/*
    - results.xml
  discard-paths: yes

cache:
  paths:
    - env/
    - ~/.cache/pip
